server:
  port: 8081
spring:
  application:
    name: hmdp
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # useAffectedRows=true 更新mysql时返回受影响的行数
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useAffectedRows=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
  # redis配置
  redis:
    # host: 192.168.1.107
    host: 127.0.0.1
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  # rabbitmq配置
  rabbitmq:
    host: 127.0.0.1
    username: root
    password: 123456
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true # 开启发送失败退回
    template:
      mandatory: true
    listener:
      simple:
        prefetch: 1 # 每次只能获取一条消息，处理完成才能获取下一个消息，能者多劳
        acknowledge-mode: manual
        retry:
          enabled: true # 开启消费者失败本地重试
          initial-interval: 1000 # 初始的失败等待时长为1秒
          multiplier: 1 # 失败的等待时长倍数，下次等待时长 = multiplier * last-interval
          max-attempts: 3 # 最大重试次数
          stateless: true # true无状态；false有状态。如果业务中包含事务，这里改为false
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.hmdp: debug